### PR TITLE
loop-slip-tap.sh: Use directory of loop-slip-tap.sh

### PR DESCRIPTION
**Pull request by pfl**
Use the directory of loop-slip-tap.sh to look for the tunslip6
executable. Do a loop for finding it, first look into the
current directory, then in the directory for the shell script
and last in $ZEPHYR_BASE/../net-tools as before.

Also check that tunslip6 has execute bit set.

Signed-off-by: Patrik Flykt <patrik.flykt@linux.intel.com>

### CODE REVIEW

**Comment by pfl** [comment]
This does not look like an error in the code:

shippable_retry sudo docker pull zephyrprojectrtos/ci:master.27
Error response from daemon: manifest for zephyrprojectrtos/ci:master.27 not found
retrying 1 of 3 times...
Error response from daemon: manifest for zephyrprojectrtos/ci:master.27 not found
retrying 2 of 3 times...
Error response from daemon: manifest for zephyrprojectrtos/ci:master.27 not found
retrying 3 of 3 times...

**Comment by jukkar** [comment]
recheck

**Comment by jukkar** [comment]
@pfl can you resubmit, for some reason shippable does not want to recheck

**Comment by pfalcon** [comment]
> for some reason shippable does not want to recheck

I noticed that yesterday in the main repo too. @nashif : FYI

**Comment by jukkar** [comment]
Ok, the shippable error does not seem to be related to this pr so force merging this.

**Pull request merged**
